### ISSUE TITLE
Revise description

### ISSUE THREAD

**Issue by sr320** [jheare/OluridaSurvey2014#10]
more than just Temp data .. 
maybe .. Raw Data and R scripts to generate manuscript figures

**Comment by sr320** [comment]
@jheare still needs attention

**Comment by jheare** [comment]
I'm not sure where you are seeing the Temp Data bit in the description. The description I read says 

This repository includes raw data and R scripts used to generate figures for Heare et al. "[**Evidence of _Ostrea lurida_ population structure in Puget Sound, WA**](https://peerj.com/preprints/704v1/)"

**Comment by jheare** [comment]
Updated, I made a slight variation on what you wrote to include Statistical analysis as well as figure creation
