### ISSUE TITLE
Death and status

### ISSUE THREAD

**Issue by sr320** [jheare/OluridaSurvey2014#14]
What does "death" and "status" refer to in the KMdataAll.csv file.

**Comment by jheare** [comment]
Death refers to the time point which death was recorded, Status is
Live/Dead in binary (1=Live, Dead=0).

**Comment by sr320** [comment]
Thanks! So time point refers to ...?

**Comment by jheare** [comment]
Number of months from outplant.

**Comment by sr320** [comment]
Thanks!
